#!/bin/bash

sql_password="Jessie was here"
mysqldump -u root -p TerpSecure > database_dump.dat < echo $sql_password

if [ ! -e "./database_TerpSecure.dat" ]
then
	echo "Error exporting MYSQL database."
	exit 1
fi


git add database_dump.dat
git commit
git push
