#!/bin/sh

# Sets up the production (release) environment

if [ "$#" -gt 0 ]
then
if [ "$1" = "--help" ]
then
	echo "Sets up the production (release) environment. This includes copying "
	echo "the files from the www folder in the current working directory to "
	echo "the directory which the apache2 server is configured to serve files "
	echo "from."
	echo ""
	echo "		--purge-old	Delete all files currently in the root web "
	echo "				  directory before copying over the files "
	echo "				  from the local git repository"
	echo "		--help		Display this help text and exits"
	echo ""
	exit 0

elif [ "$1" = "--purge-old" ]
then
	sudo rm -r /var/www/*
else
	echo "Unknown option. Try --help."
	exit 0
fi
fi


# Copy website files to www root directory for the web server
sudo cp -R -v www /var/



# Import the MySQL database
#TODO
