#!/bin/sh

# Install necessary packages
#sudo apt-get update
#sudo apt-get install mysql
#sudo apt-get install php5 php5-mysql
#sudo apt-get install python3-all

#sudo pip-3.2 install flask


# ?????????
#git ?


# Copy website files to www root directory for the web server
sudo cp -R -v www /var/


# Download reactjs tutorial
#git clone http://github.com/reactjs/react-tutorial.git


# Setup MYSQL
#mysql_secure_installation
#sudo mysql_install_db
